- ui/src/app/(pages)/share/[uploadId]/page.tsx
Increased the width of the container in share page
- Changed the width of the container box
- share/[uploadID]/page.tsx
- Get more screen space
- It's an improvement 
Tested the UI for the update
> increased the width of share page container

- ui/src/app/(pages)/page.tsx
Fixed the progress bar issue for large files
Fixes #74
- changed in the page.tsx for the landing page that calculates the aggregate percentage now
- to fix the error of unexpected progress percentage
- It was a bug fix
Yes, its tested from UI directly
> fixed progress percentage for large file issue

- middleware/main.py
Added Upload with text before the first file name in the topic
Fixes #76
- changed in the middleware to keep Upload with in the topic name
- To give a decent topic that is readable and identifiable to the user
- It was an improvement
Yes
> added upload with name in the topic

- ui/src/components/header.tsx
Fixed the UI alignment issue.
Fixes #79
- changed the name to be only first name in header component
- To fix the alignment issue
- Its a fix
Yes
> fixed small screen alignment issue

- ui/src/components/header.tsx
Smaller text for name
- Made the text smaller
- To fix alignment
Yes
> smaller name text

- middleware/main.py
- ui/src/app/(pages)/page.tsx
Adds send to email directly option
Fixes #82 
- Removed share email as source checkbox
- Added user name to webhook
- Added receiver email column in upload_metadata
- send user id to /postUpload
- send email to user if email is entered
- To enable sending files to email directly
- Its a feature
Yes
> added share to email feature

- middleware/main.py
Sorted history based in time created
Fixes #78 
- Sorting the history list of dictionary based on creation date
- To make it easy for the user to find the latest upload in history
Yes
> added history to be sorted in descending order

- middleware/main.py
- ui/src/app/(pages)/page.tsx
- ui/src/components/header.tsx
fixes the reported and known bugs
Fixes #94 
- Removed the dependency of user table for some time
- Minor email formatting changes
- Fixed the input not getting selected in first time or deselecting itself issue in drawer
- Fixed text format of logout dropdown
- Fixing the bugs
Yes
> fixed reported and known bugs

- README.md
Updated readme for terraform as per the feedback received
- changed readme file for resolving the confusion of terraform/cloud and terraform/local, which one to use for local running, i.e terraform/cloud
- Based on the feedback
No need
> updated readme for terraform

- README.md
Changed in the Readme to make it more understandable
- Readme file
- Making it more understandable
No needed
> Ambujraj-patch-1

- middleware/template.yaml
- ui/.env.example
- ui/src/app/(pages)/(protected)/history/page.tsx
- ui/src/app/(pages)/page.tsx
- ui/src/app/(pages)/share/[uploadId]/page.tsx
- ui/src/app/(pages)/upgrade/page.tsx
- ui/src/components/header.tsx
Add API key to the API Gateway and frontend changes to add api key in the request
Fixes #101 
- Added API key and Usage plan in SAM template
- Added api key in UI in request headers
- To enable DDoS attack security
- Its an improvement
Not yet
> added API key to APIs

- middleware/template.yaml
Fixing issues of API key addition
- enabled api key by default
- added header in CORS
Testing in progress
> fixing bugs after testing

- ui/public/Data/terms-page-data.json
- ui/src/app/(pages)/auth/terms/page.tsx
- ui/src/app/globals.css
- ui/tailwind.config.ts
- ui/tsconfig.json
Term page is added 
- Added the terms page with some new custom color.
- tailwind config and and added some changes in global css 
- To make more functional site
- improvement
Yes being tested and here is the screenshot of the page (https://github.com/ambujraj/ByteShare/assets/32640258/163b1de2-0cb0-452e-9d51-78322b41cf73)
> Added the terms page

- ui/public/Data/terms-page-data.json
- ui/src/app/(pages)/auth/terms/page.tsx
update the welcome message and disclaimer. 
Fixes #115 
- new title will be visible
- welcome message was not properly formated and needs to trimmed and updated.
-  It a bug fix and little  improvement
Yes
> Term page with new welcome message and disclaimer #115

- .github/workflows/deploy-backend.yaml
- .github/workflows/deploy-frontend.yaml
Added GA to be called on release
Fixes #119 
- Changed github action workflows
- For calling GA only on release
No
> added github action to be called on release

- .github/workflows/deploy-frontend.yaml
minor fix in GA for frontend
- updated used variable issue
- It was a fix
No
> fixed uses issue in GA

- middleware/app/main.py
- ui/src/app/(pages)/share/[uploadId]/page.tsx
Reverts ambujraj/ByteShare#123
> Revert "added autodownload on scanning QR"

- middleware/app/main.py
Minor changes before release
- Spelling and alignment changes
Yes
> minor fixed before release

- ui/src/components/header.tsx
Fixed the implementation of hamburger button click
Fixes #(129)
- updated headers file to fixed button
- It was bug 
yes
> fixed the hamburger open on mobile devices

- ui/package-lock.json
- ui/package.json
- ui/src/app/(pages)/page.tsx
- ui/src/components/ui/scroll-area.tsx
This adds drag and drop feature along with view selected dialog that shows selected files that can also be removed from dialog.
Fixes #131 
- Added Drag and drop feature
- Added View Selected files dialog
- Added folder upload support on drag and drop
- To simplify the users upload experience.
- Its an enhancement.
Yes, locally
> Add Drag and drop feature for upload

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
Updated templates for the repository.
- Issue template and PR template
> Updated GitHub template

- ui/src/app/(pages)/(protected)/history/page.tsx
- ui/src/app/(pages)/auth/forgot-password/components/forgot-form.tsx
- ui/src/app/(pages)/auth/forgot-password/page.tsx
- ui/src/app/(pages)/auth/login/components/auth-form.tsx
- ui/src/app/(pages)/auth/login/page.tsx
- ui/src/app/(pages)/auth/logout/page.tsx
- ui/src/app/(pages)/auth/privacy/page.tsx
- ui/src/app/(pages)/auth/reset-password/components/reset-form.tsx
- ui/src/app/(pages)/auth/reset-password/page.tsx
- ui/src/app/(pages)/auth/signup/components/auth-form.tsx
- ui/src/app/(pages)/auth/signup/page.tsx
- ui/src/app/(pages)/auth/terms/page.tsx
- ui/src/app/(pages)/auth/verify-email/page.tsx
- ui/src/app/(pages)/help/page.tsx
- ui/src/app/(pages)/layout.tsx
- ui/src/app/(pages)/page.tsx
- ui/src/app/(pages)/share/[uploadId]/page.tsx
- ui/src/app/(pages)/upgrade/page.tsx
- ui/src/app/layout.tsx
- ui/src/app/not-found.tsx
- ui/src/app/robots.ts
- ui/src/app/sitemap.ts
- ui/src/authentication/appwrite/config.ts
- ui/src/components/header.tsx
- ui/src/components/loading.tsx
Added SEO optimisation to enable registering the app in search engines.
Fixes #128 
- Suggested SEO changes in the code
- To improve the SEO score in search engines
- It's an improvement
Yes
> Add SEO improvements in the UI app

- middleware/app/main.py
- ui/src/app/(pages)/(protected)/history/page.tsx
Adds edit title option in history page
Fixes #92 
- Added edit title endpoint in backend
- Added edit upload option in frontend
- To enable user to edit the title to identify the upload
- It's an enhancement
Yes, locally
> Add Edit Title option in History page

- CHANGES.md
Added CHANGES.md for the previous releases.
Fixes #148 
- Added CHANGES.md
- To have changes tracking
Not needed.
> 📝 Added CHANGES.md for older releases

- CHANGES.md
Updated CHANGES.md to version 0.2.0
> Updated CHANGES.md for version 0.2.0

- .github/workflows/deploy-backend.yaml
Fixed GA env variable issue for Backend
- Removed the space after $
Yes
> Fixed GA env variable issue

- middleware/Dockerfile
- ui/src/app/(pages)/auth/login/components/auth-form.tsx
- ui/src/app/(pages)/auth/signup/components/auth-form.tsx
- ui/src/app/(pages)/auth/verify-email/page.tsx
- ui/src/app/(pages)/page.tsx
- ui/src/app/sitemap.ts
Solves noindex issue for SEO due to the use of useSearchParams
Fixes #156 
- Removed the use of useSearchParams wherever required
- Added /upgrade to sitemap
- Fixed Dockerfile for Middleware
- Its a bug fix for SEO
Yes
> Fix noindex issue in robots due to useSearchParams

- CHANGES.md
> added changelog for 0.2.1

- ui/src/app/(pages)/(protected)/history/page.tsx
Adds toast related user experience enhancement with toasts and enabling multiple operation in toast.
- Added toast wherever required.
- Enabled toast dismiss by toast ID.
- It's an user experience enhancement
Yes, locally
> User experience enhancement in history page

- ui/package-lock.json
- ui/package.json
- ui/src/app/(pages)/(protected)/history/page.tsx
- ui/src/components/ui/alert-dialog.tsx
Adds delete confirmation dialog in history page
Fixes #172 
- Added alert dialog component
- Added confirmation dialog for delete in history page
- Added missing try catch block in handleDelete function
- To avoid accidental deletes
- It's an improvement
Yes, locally
> Add Delete confirmation dialog in History page

- CHANGES.md
Updated changelog for version 0.3.0
> Updated Changelog for version 0.3.0

- README.md
Reverts ambujraj/ByteShare#187
> Revert "Added current product video"

- ui/src/components/ui/scroll-area.tsx
Made the scroll bar invisible in view selected
Fixes #194 
- Made the width of scroll bar to 0.5
- Make it look cleaner
Yes, locally
> Invisible scroll bar in View Selected dialog

- middleware/app/api/routes/upload.py
- ui/package-lock.json
- ui/package.json
- ui/src/app/(pages)/(protected)/history/page.tsx
- ui/src/app/(pages)/page.tsx
Added date time in UI based on user's timezone
Fixes #98 
- Added time formatting with user's timezone
- Made description text smaller in home page
- To increase user experience
- It's an improvement
Yes, locally
> Add date time based on user timezone

- ui/src/app/(pages)/page.tsx
Fixed email not verified issue on immediate click of send button
Fixes #197 
- Disabling the send button till user is not loaded
- It's a fix
Yes, locally
> Fix email not verified issue

- CHANGES.md
Added 0.3.1 to changelog
- Updated changelog
> Added 0.3.1 to changelog

- ui/src/app/(pages)/page.tsx
Fixed send button being disabled on logged out user
Fixes #205 
- Added another variable for disabling send button
- It's a fix
Yes, locally
> Fixed send button disabled issue

- middleware/template.yaml
Defines endpoints individually in SAM template.
Fixes #215 
- Updated the sam template to configure all the endpoints individually.
- To have control at endpoint level
No
> Endpoints defined individually in SAM template

- CHANGES.md
Updates Changelog
Yes, locally
> Updated Changelog for 0.4.0

- middleware/app/api/services/access/aws.py
Adds X-Amz-Date header for IAM requests
> Fixed X-Amz-Date header missing

- middleware/app/api/services/secured/developer.py
- middleware/app/utils/auth.py
- middleware/template.yaml
- ui/src/app/(pages)/docs/developers/page.tsx
- ui/src/app/(pages)/page.tsx
> Release fix

- middleware/template.yaml
API key required defined in API
> API key required defined in API

- middleware/template.yaml
Added missing API key required
> Added missing API key required

- ui/src/app/(pages)/page.tsx
Added option to add more files in view selected
Fixes #248 
- Added a button in view selected that can add more files in the selected files state
- To enable users to add more files even after selecting the files
Yes, locally
> Add option to add more files in View Selected

- ui/src/app/(pages)/page.tsx
- ui/src/app/layout.tsx
Fixed the file size that was not getting updated correctly
- Updated the Add more files function
- Updated title for SEO
- It's a bug fix
Yes, locally
> Fixed file size update issue in add more files

- ui/src/app/(pages)/page.tsx
Added the missing multiple upload in Add more 
- Added multiple in upload input
- It's a bug fix
Yes, locally
> Fixed multiple upload in add more

- middleware/app/api/services/upload.py
Made RabbitMQ optional in upload
Fixes #253 
- Added try except for handling RabbitMQ error with log
- It's a bug fix
No
> Made RabbitMQ optional

- CHANGES.md
> Added changelog for 0.4.1

- ui/src/app/(pages)/page.tsx
> Minor type temp fix

- ui/src/app/(pages)/docs/developers/page.tsx
Makes the update in developer page as well
- Updated developer page
Yes, locally
> Update developer page to signify open health endpoint

- ui/package-lock.json
- ui/package.json
- ui/src/app/(pages)/page.tsx
Fixes multiple file selection delay issue
- Added debounce in file selection function
- Its a bug fix
No
> Fix multiple file selection delay issue

- middleware/app/api/services/upload.py
Temporarily removed rabbitmq usage to reduce occurring errors
- Commented rabbitmq part in code
- To temporally reduce errors
No
> Removed rabbitmq usage temporarily

- ui/src/app/(pages)/page.tsx
Fixed button click issue
Fixes #272 
- Added z index value for button
- It's a bug fix
Yes, locally
> Fix button click issue

- middleware/app/api/services/health.py
Added Appwrite in health check
Fixes #274 
- Added Appwrite healthcheck in health endpoint
- Its an addition in healthcheck
Yes, locally
> Add Appwrite in health check
